package constants

const SCHEDULER_QUEUE = "SCHEDULER_QUEUE"
const DISPATCH_QUEUE = "DISPATCH_QUEUE"
const WORKER_QUEUE_PREFIX = "WORKER_QUEUE_JOB_TYPE_"
const JOB_FIELD_KEY_PREFIX = "Job_"
const JOBS_MAP = "JOBS_MAP"
const PROCESSING_QUEUE = "PROCESSING_QUEUE"
